#!/bin/bash
lineNum=0

while read myLine
do
    sum=0
    count=0
    average=0
    lineNum=$(($lineNum + 1))
    echo "Processing line $lineNum: $myLine"

    for i in $myLine
    do
        num=$i
        count=$(($count + 1))
        echo "  Item $count: $num"
        sum=$(($sum + $num))
    done

    average=$(($sum / $count))

    echo "  Line count: $count"
    echo "  Line sum: $sum"
    echo "  Line average: $average"
done < $1
